[General]
# ============================================================
#  Miles Morales SDDM Theme — theme.conf
#  Fon şəklini buradan dəyişə bilərsiniz.
#  Mütləq tam yolu yazın, məsələn:
#    background=/usr/share/sddm/themes/miles-morales/background.jpg
# ============================================================

background=/usr/share/sddm/themes/miles-morales/background.jpg

# Blur intensivliyi (gələcək versiyalar üçün saxlanılıb)
blur=false
blurRadius=32
