monitor=,preferred,auto,1

# Startup
exec-once = waybar
exec-once = hyprpaper
exec-once = dunst
exec-once = nm-applet
exec-once = blueman-applet
exec-once = swaybg -m fill -i /home/mrcat/Pictures/wallpapers/sa.jpg

input {
    kb_layout = us
    follow_mouse = 1
}

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 3
    # Qırmızıdan mavi qradientə keçid
    col.active_border = rgba(0077ccff) rgba(00ffffff) 45deg 
    # İnaktiv borderi tünd mavi et
    col.inactive_border = rgba(002244ff)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 12
        passes = 4
        vibrancy = 0.1696
        brightness = 0.8
        ignore_opacity = true
    }
    shadow {
        enabled = true
        range = 20
        render_power = 3
        # Qırmızı kölgəni mavi kölgəyə çevirdik
        color = rgba(0077cc55) 
    }
}
#animations {
#    enabled = yes
#    bezier = web, 0.05, 0.9, 0.1, 1.05
#    animation = windows, 1, 6, web, slide
#    animation = border, 1, 10, default
#    animation = fade, 1, 7, default
#    animation = workspaces, 1, 5, default
#}

# macOS tarzı yaylanma için özel eğri
bezier = macos, 0.2, 0.9, 0.3, 1.05
animations {
    enabled = yes
    
    # "macOS" adını verdiğimiz eğriyi kullanıyoruz
    # 1. parametre: aktif mi
    # 2. parametre: hız (ms cinsinden süre)
    # 3. parametre: bezier eğrisinin adı
    
    animation = windowsMove, 1, 5, macos, slide
    animation = windowsIn, 1, 5, macos, slide
    animation = windowsOut, 1, 5, macos, slide
    animation = workspaces, 1, 6, macos, slidefade
}

dwindle {
    preserve_split = yes
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

# Window Rules
windowrule = match:class org.kde.dolphin, float on
windowrule = match:title Volume Control, float on
windowrule = match:class Alacritty, opacity 0.92 0.85
windowrule = match:class code, opacity 0.75 0.75

# Keybinds
$mod = SUPER

bind = $mod, T, exec, kitty
bind = $mod, Q, killactive
bind = $mod, M, exec, wlogout
bind = $mod SHIFT, M, exit
bind = $mod, E, exec, dolphin
bind = $mod, B, exec, firefox
bind = $mod, F, togglefloating
bind = SUPER, D, exec, mpv --no-video ~/.local/share/hypr/spider-man-customized-web-thwip-sound-effect-1_ybmate.mp3 & wofi --show drun
#bind = SUPER, D, exec, paplay ~/.config/hypr/sounds/spiderman_web.mp3 & wofi --show drun
bind = $mod, R, exec, hyprlauncher
bind = $mod, L, exec, hyprlock
bind = $mod, V, exec, code

# Screenshot (wayshot)
# -f parametresini kaldırıp dosya yolunu direkt sona ekliyoruz
# Seçerek ekran görüntüsü alma
bind = , Print, exec, ~/.local/share/hypr/ss.sh area

# Tüm ekranı alma
bind = $mod, Print, exec, ~/.local/share/hypr/ss.sh

# Mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Odak
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Workspace
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
