preload = /home/mrcat/Pictures/wallpapers/1379858.png

# Monitör ismin hyprctl'ye göre eDP-1 olduğu için bu şekilde olmalı
wallpaper = eDP-1,/home/mrcat/Pictures/wallpapers/1379858.png

splash = false
